server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    dialect: ${SPRING_DATASOURCE_DIALECT}

  jpa:
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
    open-in-view: ${SPRING_JPA_OPEN_IN_VIEW}
    database: ${SPRING_JPA_DATABASE}
    show-sql: ${SPRING_JPA_SHOW_SQL}
    generate-ddl: ${SPRING_JPA_GENERATE_DDL}
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST}
      port: ${SPRING_DATA_REDIS_PORT}
      password: ${SPRING_DATA_REDIS_PASSWORD}

  cloud:
    aws:
      credentials:
        access-key: ${CLOUD_AWS_CREDENTIALS_ACCESS_KEY}
        secret-key: ${CLOUD_AWS_CREDENTIALS_SECRET_KEY}
      region:
        static: ${CLOUD_AWS_REGION}
      s3:
        bucket: ${CLOUD_AWS_S3_BUCKET}
        base-url: ${CLOUD_AWS_S3_BASE_URL}
      stack:
        auto: false

